---

- name: Install Apache
  yum: name=httpd state=present
  
- name: Configure Apache
  template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  sudo: yes
  
- name: Restart Apache
  service: name=httpd state=restarted